#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPT_DIR/print-head

sudo echo "Extraction de $1..."

sudo tar -xf $1 -C /var/lib/docker/volumes/postgres-data/_data
