#!/bin/bash

source print-head

getopts "c:" opt $@

if [[ $opt != "c" ]]; then
	echo "Quel container voulez vous démarrer ?"
	read -p "[T]ous | [F]rontend | [B]ackend | [P]ostgres | [R]edis | [Q]uitter: " CONTAINER_TO_START
else
	CONTAINER_TO_START=$OPTARG
fi

getopts "e:" opt $@

if [[ $opt != "e" ]]; then
	ENV_FILE=".env"
else
        ENV_FILE=$OPTARG
fi

if [[ " q quitter " =~ " $(echo $CONTAINER_TO_START | tr '[:upper:]' '[:lower:]') " ]]; then echo "Programme quitté."; exit; fi

if [[ " t tous f frontend " =~ " $(echo $CONTAINER_TO_START | tr '[:upper:]' '[:lower:]') " ]]; then

	echo "Execution du container frontend..."

fi

if [[ " t tous b backend " =~ " $(echo $CONTAINER_TO_START | tr '[:upper:]' '[:lower:]') " ]]; then

        echo "Execution du container backend..."

fi

if [[ " t tous p postgres " =~ " $(echo $CONTAINER_TO_START | tr '[:upper:]' '[:lower:]') " ]]; then

        echo "Execution du container postgres..."

fi

if [[ " t tous r redis " =~ " $(echo $CONTAINER_TO_START | tr '[:upper:]' '[:lower:]') " ]]; then

        echo "Execution du container redis..."

fi

