#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source $SCRIPT_DIR/print-head

getopts "c:" opt $@

if [[ $opt != "c" ]]; then
        echo "Quel container voulez vous éteindre ?"
        read -p "[T]ous | [F]rontend | [B]ackend | [P]ostgres | [R]edis | [Q]uitter: " CONTAINER_TO_STOP
else
        CONTAINER_TO_STOP=$OPTARG
fi

if [[ " q quitter " =~ " $(echo $CONTAINER_TO_STOP | tr '[:upper:]' '[:lower:]') " ]]; then echo "Programme quitté."; exit; fi

if [[ " t tous f frontend " =~ " $(echo $CONTAINER_TO_STOP | tr '[:upper:]' '[:lower:]') " ]]; then

	docker stop frontend

fi

if [[ " t tous b backend " =~ " $(echo $CONTAINER_TO_STOP | tr '[:upper:]' '[:lower:]') " ]]; then

        docker stop backend

fi

if [[ " t tous p postgres " =~ " $(echo $CONTAINER_TO_STOP | tr '[:upper:]' '[:lower:]') " ]]; then

        docker stop postgres

fi

if [[ " t tous r redis " =~ " $(echo $CONTAINER_TO_STOP | tr '[:upper:]' '[:lower:]') " ]]; then

        docker stop redis

fi

